spring:
  application:
    name: webhook-sample

server:
  port: 8181

logging:
  file:
    name: logs/webhook-sample.log
  logback:
    rollingpolicy:
      file-name-pattern: logs/webhook-sample.%d{yyyy-MM-dd}.%i.log.gz
      clean-history-on-start: true
      max-file-size: 10MB
      max-history: 7
      total-size-cap: 1GB
  level:
    com.example.webhooksample: INFO

minio:
  endpoint: http://192.168.99.20:9000
  access-key: sbim
  secret-key: N9wyScFh7Z6jbJ
  bucket: gosd
  region: cn-shenzhen
  sts-duration-seconds: 3600
  sts-role-session-name-prefix: webhook-storage
